---
- name: Install and run Django application
  hosts: web01
  become: yes

  tasks:
    - name: Install Python 3 and pip
      package:
        name: ['python3', 'python3-pip']
        state: present

    - name: Install Django
      pip:
        name: django
        state: present