---
- name: Install Python 3 and pip
  package:
    name: ['python3', 'python3-pip']
    state: present
    
- name: Install Django
  pip:
    name: django

- name: Install git package
  apt:
    name: git
    state: present

- name: Clone Django application repository
  git:
    repo: https://gitfront.io/r/deusops/BC6tmrogTrbh/django-filesharing.git
    dest: /opt/django-filesharing
    force: yes

- name: Install Python requirements for Django application
  pip:
    requirements: /opt/django-filesharing/requirements.txt

- name: Set permissions for settings.py file
  ansible.builtin.file:
    path: /opt/django-filesharing/filesharing/settings.py
    mode: "0666"

# - name: Найти и заменить ALLOWED_HOSTS
#   ansible.builtin.replace:
#     path: /opt/django-filesharing/filesharing/settings.py
#     regexp: '(ALLOWED_HOSTS\s*=\s*\[)([^]]+)(\])'
#     replace: 'ALLOWED_HOSTS = ["{{ hostvars["web01"]["ansible_host"] }}"]'



- name: Удалить строку MEDIA_URL = '/media/'
  replace:
    path: /opt/django-filesharing/filesharing/settings.py
    regexp: 'MEDIA_URL\s*=\s*''/media/'''
    replace: ''

- name: Вставить новое значение MEDIA_URL
  lineinfile:
    path: /opt/django-filesharing/filesharing/settings.py
    insertafter: EOF
    line: "MEDIA_URL = '/mnt/nfs/'"





# - name: Modify MEDIA_URL in settings.py
#   replace:
#     path: /opt/django-filesharing/filesharing/settings.py
#     regexp: "'MEDIA_URL': '.+'"
#     replace: "'MEDIA_URL': '/mnt/nfs'"

- name: Run Django application in background
  command: python3 /opt/django-filesharing/manage.py runserver 0.0.0.0:8000 --noreload
  args:
    chdir: /opt/django-filesharing
  async: 0
  poll: 0


