---
- name: Run Django application
  hosts: web01
  become: yes

  tasks:
    - name: Clone Django application repository
      git:
        repo: https://gitfront.io/r/deusops/BC6tmrogTrbh/django-filesharing/
        dest: /opt/django-filesharing

    - name: Install Django application dependencies
      pip:
        requirements: /opt/django-filesharing/requirements.txt

    - name: Apply Django migrations
      command: python /opt/django-filesharing/manage.py migrate

    - name: Run Django application
      command: python /opt/django-filesharing/manage.py runserver 127.0.0.1:8000
      async: true
      poll: 0
