- name: Install and configure NFS server
  include_tasks: NFS_server.yml
  tags: 
    - nfs_server
  when: "'files' in group_names"

- name: Install and configure NFS client
  include_tasks: NFS_client.yml
  tags: 
    - nfs_client
  when: "'web' in group_names"
