---
- name: Install NGINX
  apt:
    name: nginx
    state: present

- name: Copy NGINX configuration file
  template:
    src: nginx_proxy.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: Reload NGINX
