---
- name: Run main tasks on files hosts
  hosts: files
  become: true
  roles:
    - role: ./ansible/roles/nfs
      tags:
        - nfs_server

- name: Run tasks on web hosts
  hosts: web
  become: true
  roles:
    - role: ./ansible/roles/nfs
      tags:
        - nfs_client

- name: Deploy NGINX, Django, and NFS configurations
  hosts: web01
  become: yes
  roles:
    - role: ./ansible/roles/nginx
    - role: ./ansible/roles/django
    - role: ./ansible/roles/nfs_web_files
  
